title: "Jaime (Feng-Yuan) Hsu"
author: "Blog Author"
description: "Jaime Hsu, UT Austin"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: About Me, icon: home }
  - {file: "Research.md", title: Research, icon: pen}
  - {file: "CV_Jaime.pdf", title: CV, url : "https://jaimehsu.github.io/CV_Jaime.pdf", icon: file}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {file: "index.md", title: About Me, icon: home }
  - {file: "Research.md", title: Research, icon: pen}
  - {file: "CV_Jaime.pdf", title: CV, url : "https://jaimehsu.github.io/CV_Jaime.pdf", icon: file}
  - {title: Mail, icon: envelope, url: "mailto:jfhsu@utexas.edu"}
  - {title: Github, icon: github, url: "https://github.com/jaimehsu"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
